### ISSUE TITLE
Suggestion: add a parameter to enable subsite creation of fields and content types.

### ISSUE THREAD

**Issue by levalencia** [OfficeDev/PnP#1021]
Cross reference:
https://www.yammer.com/itpronetwork/#/Threads/show?threadId=555351878

When debugging the provisioning engine we noticed there is an if for not processing the content type and fields on subsites, however in our scenario it was required because the app had to be installed on a subsite, and we had lookpfields to lists on the subsite.

We had to modify 3 parts of the code in our local project and I didnt want to create a pull request as you know better what other impact could have:

We commented out the IF here:
https://github.com/OfficeDev/PnP/blob/dev/OfficeDevPnP.Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectContentType.cs#L24

Also here:
https://github.com/OfficeDev/PnP/blob/dev/OfficeDevPnP.Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectField.cs

and here: 
https://github.com/OfficeDev/PnP/blob/dev/OfficeDevPnP.Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectLookupFields.cs#L34
We changed it to the subweb instead of rootweb

Maybe this flag could be added on the applyprovisioningtemplate method

**Comment by VesaJuvonen** [comment]
We have done intentional decision not to support site columns and content types created on the sub site level. This is due the fact that this design is NOT recommended and was never recommended in the farm solution models either. 

Problem with the sub site created content types and site columns is that they do not have references on the site collection instances, which then means that you can't update site collection from one location and are forced to loop in all also all sub sites when you apply any changes on the content types and site columns... which causes additional costs and time needed for any operations.

This same challenge was there already in the farm solutions and we have always recommended to create content types and site columns using site scoped feature at site collection level and then push those to be used in the sub sites using references. This way you can push updates on the content types and site columns at the site collection level simply by referencing those in the site collection root and then push updates to children (instances in sub sites and lists).

Due above justification - will close the issue.
