### ISSUE TITLE
Add-SPOFile doesnt generate .aspx when Masterpage is uploaded

### ISSUE THREAD

**Issue by kolliparachandra** [OfficeDev/PnP#1037]
Add-SPOFile doesnt generate .aspx when Masterpage is uploaded to a sub directory underneath _catalogs/masterpage/mycompany/masterpages. It works fine for display templates and Page layouts works with Add-SPOHtmlPublishingPageLayout.

**Comment by arangas** [comment]
I've tested this using both Add-SPOFile and Add-SPOMasterPage both to _catalogs/masterpage and to a subfolder. I could repro the issue in every case.

The crux of the issue appears to be that the PnP library doesn't support uploading HTML master pages, only HTML page layouts.

**Comment by VesaJuvonen** [comment]
thx @arangas for confirming this - appreciated. We do not really support html template model, like with design packages in the engine. This is actually by design. What we suggest you to do for these scenarios is to use the html model in development, but use only master page in production. This will reduce also possible future challenges around this.

We absolutely welcome contributions on this area as pull requests or we can have more detailed discussion around the approach in PnP Yammer group at http://aka.ms/OfficeDevPnPYammer.
