### ISSUE TITLE
Provisioning: List Instances export / import missing functionality

### ISSUE THREAD

**Issue by jeroenvanlieshout** [OfficeDev/PnP#1094]
Yesterday I tested the provisioning engine to see if it supports list creation well for looking if its suitable to use in a business case. A few things are not working as expected/missing:
- Content Types: When on the original site where the template is created from, the OOTB Content Types are removed from a list, they reappear on the site where the template is applied to. The engine recreates a list with the base list template but doesn't remove/adjust OOTB content types. Some implementation for this seems to be missing as there is already some code to remove some content types.
- Views: When a default view like All Items is adjusted in the source site which is exported, the export contains this view. But when imported this view already exists (based on list template used for list creation) and isn't overwritten/adjusted with the exported view, but a new one is created instead. This is unwanted behavior as the original list doesn't have this.
- Indexed Fields: The import/export functionality doesn't provide the ability to take care of indexed fields. This functionality would be very usefull to incorporate.
- Metadata Navigation: On lists you can set metadata navigation, but the provisisioning engine seems not to support this, will this be built-in in future?

**Comment by VesaJuvonen** [comment]
thx Jeroen, sorry for the massive delay on getting this processed. We have implemented significant improvements on these areas during our journey. If there's any specific issues around reported topics are still needed, would suggest to create an issue to PnP Core library at https://github.com/OfficeDev/PnP-sites-core, so that we do get these into account with future development.
