### ISSUE TITLE
Provisioning Engine Feature Request - Custom Permission Levels

### ISSUE THREAD

**Issue by mahajangaurav** [OfficeDev/PnP#1107]
It will be great if GetProvisioningTemplate and ApplyProvisioningTemplate could be updated to include custom permission levels as well, when the commands are being invoked at the site collection level.

**Comment by robi26** [comment]
Yeah, would be great to see that feature. Looking for a possibility right now...

**Comment by VesaJuvonen** [comment]
thx for the suggestion. Right now we are not going to implement native support for this, since we consider this requirement to be relatively rare. It's indeed sometimes required, but it's not in the roadmap of the Core team. You could implement support for this with extensibility provider. Solution which will take slightly longer is native support, since we will need to get this included in the provisioning schema. In that case, we'd suggest you to create an issue to provisioning schema repository at https://github.com/OfficeDev/PnP-provisioning-schema/issues
