### ISSUE TITLE
Loading termset failed

### ISSUE THREAD

**Issue by MaikvanderGaag** [OfficeDev/PnP#1144]
In a provider hosted app we are using the Taxonomy control. In some situations it will give us the error that loading the temset failed. 

What can be done to pin point this error or what could be wrong. Because the errors does not occur every time.

**Comment by VesaJuvonen** [comment]
Most likely issue is permission differences around the end users. Since this is really old issue, hoping that you have been able to fix the issue. In general we would recommend to use the PnP Yammer group for questions at http://aka.ms/OfficeDevPnPYammer. Will close this now, but if this is still an issue, let's first have a discussion in Yammer.
