### ISSUE TITLE
Error building ExternalSharingTimer

### ISSUE THREAD

**Issue by bassemfg** [OfficeDev/PnP#1210]
When we download the latest version of the ExternalSharingTimer solution and try to build it, we get an error that the UserId member in the ExtUser object does not exist. We can see another member called UniqueId. Is this the same? Also, the UserId was an integer and the UniqueId is a string. Any thoughts?

**Comment by VesaJuvonen** [comment]
Since project was missing a nuget package reference, it used a version which you had installed locally on your machine to GAC. This resulted most likely a version mismatch. We have now added reference to Nuget package and things are working properly.

Sorry for the massive delay on this - got buried on questions. If you have similar issues in future, feel free to keep on pushing on the question as well in GitHub or in Yammer. Hopefully you were also able to figure this one out earlier by yourself.
