### ISSUE TITLE
Missing references/dependencies in Provisioning.Cloud.Async.WebJob

### ISSUE THREAD

**Issue by BRM013** [OfficeDev/PnP#1241]
Sorry if this is not an issue, and given that I can't find anyone complaining about it I suspect not but I have tried to download PnP-master and build the Provisioning.Cloud.Async.WebJob solution and there seems to be missing references everywhere.

The Provisioning.Cloud.Async.WebJobWeb project is complaining about "SharePoint" missing from the Microsoft namespace. 

I think I managed to fix the issue but I had to remove and readd the Microsoft.SharePointOnline.CSOM nuget package. I also had to add the package to a couple of other projects. This seems odd.

Another sidebar, I opened the solution in Visual Studio 2013 and it had to upgrade a project. Is that right either?

**Comment by VesaJuvonen** [comment]
Thx for reporting this. We did fix this as part of the January 2016 release. Solution had direct CSOM references and should have been using Nuget package, like you noted in your issue description. 

On the VS2013 case - this is most likely since solution had some references to VS2015 already and when you open that in older version, Visual Studio performs some updates. Does not however really cause any issues.
