### ISSUE TITLE
NuGet: Remove Dependency to AppForSharePointWebToolkit

### ISSUE THREAD

**Issue by retostadelmann** [OfficeDev/PnP#1261]
As the OfficeDevPnPCore15 NuGet Package doesn't use the TokenHelper.cs and the SharePointContext.cs File we suggest to remove the dependency to AppForSharePointWebToolkit and just use a Package with the references alone (Like the OfficeDevPnPCore16 Package) or just doesn't specify a dependency to any client assembly, because if you want to do something with CSOM, you're gonna need that assemblies anyway, so let the users take care of how they inject the CSOM assemblies into their project. 

We have to delete these files manually everytime we use the pnp nuget package, and on update they get injected again, and we have to delete them again, as these files are not needed.

**Comment by VesaJuvonen** [comment]
Thanks for the input. Will discuss this with the team and we'll follow up on the issue.

**Comment by retostadelmann** [comment]
I saw that on the current you even mentioned it. 
Nuget package for SPO has also dependency on AppForSharePointOnlineWebToolkit to get SharePointContext and TokenHelper automatically 
http://dev.office.com/blogs/PnP-Jan-2016-Release 

What was the reason to keep the dependency to the web toolkit?

**Comment by VesaJuvonen** [comment]
We aligned the Online Core component to on-premises one to provide consistency. Based on discussions in latest Office hours and with other community members, there's two sides of this story. Some would like to keep these files in the Nuget so that they are easily available when needed. Deletig them away from project when not needed is not nice, but it seems that we would have more requests on keeping them in there than getting them away. There's two sides on this discussion and due the oob nuget structure, we can't really find optimal setup. 

We are working on possible new oob Nuget structure in engineering and if we can differentiate TokenHelper and other guys to isolated Nuget for each environments (SPO, SP2013, SP2016) and then have specific CSOM versions per environment, we can more easily provide the right options for the community.

One side of the story is also the maturity of the community around Nuget packages. We keep on getting requests on getting all what's needed on the PnP Core Nuget, so that getting started is easy. This is understandable considering the possible "nuget hell", but not optimal necessarily for those who would like to have more granular setup.

Let's continue the discussion on this one in Yammer.
