### ISSUE TITLE
Permission on Office 365

### ISSUE THREAD

**Issue by luantpk** [OfficeDev/PnP#1264]
Hi, I'm trying to use Provisioning.Framework.Console from PnP and run it my site Office 365, I also getting "You do not have permission to perform this action or access this resource". Please any help me. Thanks.

**Comment by VesaJuvonen** [comment]
This seems like a typical permission challenge. Notice that Provisioning.FrameWork.Console uses direct access on the tenant with given account, which means that you should have high permissions on the site collection which you are using to be able to to extract it.

Since this is more a question and usage support, rather than actual issue, would suggest that we move the discussion around this to PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. We have more than 3600 other active PnP users supporting each other there, so you'd get faster support on the question.

Yammer is simply more suitable for discussions. I'll close up the question and we can open an actual Issue if we can locate a bug in the code or something similar.
