### ISSUE TITLE
Samples still use removed assemblies folder

### ISSUE THREAD

**Issue by pascalberger** [OfficeDev/PnP#1275]
Before splitting up the PnP repos the repo contained an Assemblies folder. With the splitting of the repositories it was moved to the [PnP-Site-Core](https://github.com/OfficeDev/PnP-Sites-Core/tree/master/Assemblies) repository. But there are still samples in this repository which contain references to this assemblies folder (eg. [Core.UserProfiles.Sync](https://github.com/OfficeDev/PnP/blob/master/Samples/Core.UserProfiles.Sync/Core.UserProfiles.Sync/Core.UserProfiles.Sync.csproj#L67).

I can clean this up in a PR but I don't know what the idea is regarding this references and where they should reference too. 

Maybe it would be a good idea to bring the Assemblies folder also back to this repository.

**Comment by pascalberger** [comment]
@VesaJuvonen Any opinion about this?

**Comment by VesaJuvonen** [comment]
PRs for the updates are fine. We absolutely should update samples and solutions in the PnP repository to use Core component with Nuget package, not with project references. There should not be that many of these, but seems that at least few got through after re-organization.

**Comment by pascalberger** [comment]
@VesaJuvonen But for example [Core.UserProfiles.Sync](https://github.com/OfficeDev/PnP/blob/master/Samples/Core.UserProfiles.Sync) requires `Microsoft.Online.SharePoint.Client.Tenant.dll` and this couldn't be resolved with using Core NuGet package. Or am I missing something?

**Comment by VesaJuvonen** [comment]
This is now fixed in the dev branch with the #1289 submission. Tenant object is included in the latest Nuget package (http://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM), so that everything works with them - no reason for direct assembly references. Thx for reporting and please do report also if you find other old reference issues. You'll be noted already based on this in the release notes, since without your input, this sample would have stayed broken.
