### ISSUE TITLE
Localize with Microsoft.SharePoint.Client v15

### ISSUE THREAD

**Issue by jeremyDaniel** [OfficeDev/PnP#1288]
Hi according from this page https://msdn.microsoft.com/en-us/library/office/mt203989.aspx

T thought that i could set the site columns title resource property. (on SharePoint 2013 on premise) but it seems that this possibility is missing on the Microsoft.SharePoint.Client.dll  15.0.4779.1000
So we can suppose that the February realease of the provisionning engine (that support localizations) will not work on premise?
Do you have any solution to my problem?
Merci bien et bonne journee!

**Comment by VesaJuvonen** [comment]
Hi Jeremy,
since this is not really an issue, rather a question, would appreciate to move the discussion to PnP Yammer at http://aka.ms/OfficeDevPnPYammer. 

In general on-premises CSOM does not support those Resource properties right now, which means that we cannot also use them in PnP Provisioning engine. Localization support means that if you have any labels in the templates, like list names, field names, content type names etc. You can do translation of those labels based on the language of the site where the template is applied.
