### ISSUE TITLE
is there a way to save the mail REST response as email file (eml or msg file) ?

### ISSUE THREAD

**Issue by raalahmmad** [OfficeDev/PnP#1306]
Hi,
is there a way to save the mail REST response as email file (eml or msg file) ?

Thanks

**Comment by VesaJuvonen** [comment]
We would recommend to have any technical questions submitted through the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer, so that the community could help on the questions. I'm not quite sure on the details of the question, but you can certainly read the REST response in your code, for example in Azure and save that as a specific file type to other location. 

There's however no SharePoint specific APIs for this, so it's pure .NET operation.
