### ISSUE TITLE
Tokenize issue in template creation for ComposedLook

### ISSUE THREAD

**Issue by ellfoo** [OfficeDev/PnP#1371]
I've noticed a problem when extracting a ComposedLook from a url located on https://{company}.sharepoint.com. It decides to tokenize '/' as {site} causing an OutOfRangeException in GetComposedLookFile (relying on a forward slash in asseturl).

{themecatalog}/15/palette.spcolor becomes {themecatalog}{site}15{site}palette.spcolor.

This is the temporary fix which works before running extraction of the template;
```c#
                    var composedLookPropertyName = "_PnP_ProvisioningTemplateComposedLookInfo";
                    if (ctx.Web.PropertyBagContainsKey(composedLookPropertyName))
                    {
                        var value = ctx.Web.GetPropertyBagValueString(composedLookPropertyName, "");
                        if(value.Contains("{themecatalog}") || value.Contains("{site}"))
                        {
                            var tokenValue = ctx.Web.ServerRelativeUrl == "/" ? "" : ctx.Web.ServerRelativeUrl;
                            value = value.Replace("{themecatalog}", tokenValue + "/_catalogs/theme").
                                Replace("{site}", tokenValue);
                            ctx.Web.SetPropertyBagValue(composedLookPropertyName, value);
                        }
                    }
```

**Comment by ellfoo** [comment]
This quick and dirty fix in turns needs the following "fix"
```c#
   foreach(var f in template.Files)
      f.Folder = f.Folder.Replace("{site}{site}_catalogs{site}theme", "{themecatalog}");
   if (template.ComposedLook != null)
      template.ComposedLook.ColorFile = template.ComposedLook.ColorFile.Replace("{site}/_catalogs/theme", "{themecatalog}");
````
Hopefully this would not be needed.

**Comment by VesaJuvonen** [comment]
thx ellfoo,
we did some refactoring on this around April 2016 release and it should be behaving properly now. If you do however find issues around this still, please report the issue in the PnP Sites Core repository at https://github.com/OfficeDev/PnP-sites-core.

We did indeed have a bug on root site extraction, since that was never tested in our test cases... thinking was that you'd always have a template site under /sites/ path. Even though using root site can be a rare thing, it absolutely should work still.
