### ISSUE TITLE
NotificationURL Verify

### ISSUE THREAD

**Issue by irfan4sial** [OfficeDev/PnP#1374]
Hi All,
Anyone help me how I will do notification callback register or verify for subscriptions?
When i provide:
**    json_object = {
        "@odata.type":"#Microsoft.OutlookServices.PushSubscription",
        "Resource": "https://outlook.office.com/api/v2.0/me/events",
        "NotificationURL":"https://mybookafy.com/notifications",
        "ChangeType":"Created, Updated, Deleted",
        "ClientState":"36228645-58b5-4d73-98a6-1b9ac535680c"
    }**
then show error message:

**ErrorInvalidParameter\",\"message\":\"Notification URL 'https://mybookafy.com/notifications?validationtoken=NzE1NThmYmQtMWlZTAtYTNkNmY5MDBjNzNh' verification failed 'System.Net.WebException:**

How I fix this.
Thanks

**Comment by VesaJuvonen** [comment]
I'd suggest to use Yammer for these specific questions around API usage. This Issue list is around the samples in the PnP. Would also have a look on following https://github.com/OfficeDev/PnP/tree/master/Samples/OutlookNotificationsAPI.WebAPI and the associated videos on making things happen. 

If that does not give you the solution, please use the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer for questions, since this is not specifically an issue.
