### ISSUE TITLE
BrandingExtensions.CreateComposedLookByName

### ISSUE THREAD

**Issue by rjv-swc** [OfficeDev/PnP#1385]
The CreateComposedLookByName method assumes users will only create composed looks at the root site. When generating the paletteUrl it concatenates the current web.ServerRelativeUrl with the THEMES_DIRECTORY and the given file name. if we are on a sub site this url is invalid since themes can only live in the root.

**Comment by VesaJuvonen** [comment]
thx Roberto, seems like a valid issue and we absolutely need to get this fixed together community contributors. Since we track Core component issues directly in the Core Component repository, would appreciate if you'd create this issue there. 

Core component GitHub repository and issue list for that can be found from https://github.com/OfficeDev/PnP-sites-core/issues. thx.
