### ISSUE TITLE
GetProvisioningTemplate from app context returns incomplete template

### ISSUE THREAD

**Issue by romslo** [OfficeDev/PnP#1388]
When I run ctx.Web.GetProvisioningTemplate() with hard coded SharePointOnline credentials in a console app, I get a complete provisioning template.
When I do the same from a SharePoint app context in a provider hosted app, the returned template is incomplete. E.g. the Pages property has 0 elements.

**Comment by VesaJuvonen** [comment]
There are some differences on information what can be accessed with user credentials or with app-only permissions, but to be able to reproduce the issues, we would need more information around what did you had in the page and what kind of site this was. Basic scenarios for the export and import do work with both options, so having this additional information would be needed to understand what actually happened in your case. 

- SharePoint Online or on-premises (what version)?
- What was the site definition in site?
- What kind of information (web parts and content) was on the page?

**Comment by VesaJuvonen** [comment]
Hi romslo,
we would like to get this processed, but would need some additional details to understand how to reproduce the issue. If this is still an issue, would you create this an issue directly to the PnP Core Component repository, so that we can assign that properly to our Core team. thx. You can find PnP Core Component repository from https://github.com/OfficeDev/PnP-sites-core.
