### ISSUE TITLE
Cannot find stub for type with id "{ec5e0a70-0cc3-408f-a4dc-1bb3495aac75}". The specified server may not support APIs used in this operation.

### ISSUE THREAD

**Issue by deimos1986** [OfficeDev/PnP#1410]
Hello!
I'm trying to execute code sample https://msdn.microsoft.com/en-us/library/office/mt604898.aspx against on-premises SharePoint Foundation 2013 with December 2015 CU installed. Unfortunately I'm getting error 

> Cannot find stub for type with id "{ec5e0a70-0cc3-408f-a4dc-1bb3495aac75}". The specified server may not support APIs used in this operation.

The exception is thrown while calling
`ctx.Web.GetProvisioningTemplate(ptci);`
Please, help me troubleshoot the issue.

**Comment by VesaJuvonen** [comment]
Majority of the samples, like this one, have by default SP Online CSOM referenced to them, including SharePoint Online version of the PnP Core Nuget package. This will result above exception, since there are some properties or methods in the SPO CSOM, which do not exist in the on-premises.

What you should be doing is updating the solution to use on-premises CSOM and on-premises PnP Core component. You can do this by removing current CSOM assembly references and updating the PnP Nuget to point to https://www.nuget.org/packages/OfficeDevPnPCore15 Nuget.

You can find more information on the versions and this issue for example in following resources
- http://dev.office.com/blogs/using-correct-csom-version-for-sharepoint-customizations
- http://dev.office.com/blogs/sharepoint-CSOM-versioning-for-your-customizations

**Comment by deimos1986** [comment]
Thanks, but I had already done that before testing the solution. Actually I've created new console app, installed the NuGet (on-premises) and copied code into my main () method. So the references should be OK. Regarding articles you suggested: I'm building the solution on my dev farm so I'm using local CSOM dll from ISAPI only and talk to the local farm only so the issue seems not to be related to DLLs from different farm version.Any thoughts?
