### ISSUE TITLE
SharePointPnPCore2013 v. 2.4.1605 - ctx.Web.GetProvisioningTemplate();

### ISSUE THREAD

**Issue by dariuszbz** [OfficeDev/PnP#1436]
Hello,

i've already asked this q. on yammer

#### Which PnP repository to report the issue?
I download NuGet SharePointPnPCore2013 v. 2.4.1605

#### Category
[ ] Bug
when i try to get template xml i get the error

Field or property "NoCrawl" does not exist.

#### Environment
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

Microsoft SharePoint Server 2013  
 15.0.4569.1506 
 Update for Microsoft SharePoint Enterprise Server 2013 (KB3114726) 64-Bit Edition 
 15.0.4797.1001 Installed 
 Security Update for Microsoft SharePoint Enterprise Server 2013 (KB2737989) 64-Bit Edition 
 15.0.4701.1000 Superseded 
Feb. 2016 CU (ubersrv2013-kb3114726-fullfile-x64-glb)

#### Expected or Desired Behavior
I need to download existing schema (xml template), and after this i need to add new lists, CT, etc. After this i need to provision using PnP the new artefacts.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using PnP. We tried the issue on our own testing environment and we cannot reproduce it. Can you help us to investigate it? What version of CSOM do you have? Are you using PowerShell or .NET code? If you are in Visual Studio with .NET code, can you double-check the reference in the project's references? Thanks.

**Comment by VesaJuvonen** [comment]
Hi dariuszbz,
any news on requested additional information?

**Comment by dariuszbz** [comment]
Hello :)

 

Thank You.

 

Yes – how we can implement localization (Columns name, and description for each variation must be localized) using pure PnP, without custom code ?

Any suggestions most welcome.

 

 

 


Cheers



	
Dariusz Bzówka, mobile +48 607 499 183

Enterprise Services, Consultant

MSCD – Azure Solutions Architect

MSCD – Sharepoint Application

MSCD – Web applicatios

**Comment by VesaJuvonen** [comment]
Hi dariuszbz,
if you have any specific questions around PnP or SharePoint development topics, would suggest to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Deleted the email response from GitHub for now, since that contained email and phone number details, which you might not want to get shared openly. 

Paolo was though asking additional details around this issue, which you reported around PnP Core component - https://github.com/OfficeDev/PnP/issues/1436. Issue around the NoCrawl is typically caused by wrong CSOM version to be referenced in the code, unless you are using PowerShell. 

thx. for the additional details advance.

**Comment by VesaJuvonen** [comment]
No response on the additional details, so concluding that the issue is around the conflicting version of CSOM being used. See more details on the exact challenge and correct CSOM version for your environment from https://dev.office.com/blogs/using-correct-csom-version-for-sharepoint-customizations.
