### ISSUE TITLE
OD4B.NavLinksInjection not working for OneDrive

### ISSUE THREAD

**Issue by courtzzz** [OfficeDev/PnP#1442]
#### Which PnP repository to report the issue?
https://github.com/OfficeDev/PnP/tree/master/Samples/OD4B.NavLinksInjection/

#### Category
[Bug]

#### Environment
Office 365 / SharePoint Online

#### Expected or Desired Behavior
Seeing links on OneDrive?

#### Observed Behavior
No links shown on one-drive

#### Steps to Reproduce
Deployed the app and can see the links on SharePoint, but not onedrive?

![onedrivenotworking](https://cloud.githubusercontent.com/assets/384711/15769394/04c1fb48-299e-11e6-96ea-580b5a809566.PNG)

And if we can't do it this way, is it possible to put any html/js on the onedrive site?

**Comment by courtzzz** [comment]
I even tried this:

https://github.com/OfficeDev/PnP/tree/master/Solutions/Provisioning.OneDrive

But it didnt work. Im really only trying to get the scriptlink to work but it doesnt seem it does.

I call the following in a console app:

` using (var context = new ClientContext("https://name-my.sharepoint.com/personal/admin_name_onmicrosoft_com"))
            {
                context.Credentials = new SharePointOnlineCredentials("admin@name.onmicrosoft.com", secure);
                context.Load(context.Web, w => w.Title);
                context.ExecuteQuery();


                    Web rootWeb = context.Web;
                    context.Load(rootWeb);
                    context.ExecuteQuery();

               
                    rootWeb.AddJsLink("OneDriveCustomJS", "https://www.sharepointtutorials.net/scripts/player/userScripts.js");`

Can we confirm adding js to a onedrive site still works? If so is there any way I could get a quick code sample?

**Comment by courtzzz** [comment]
OK. so it seems classic onedrive still works:

/_layouts/15/start.aspx#/Documents/Forms/All.aspx

however the new one doesnt:

/_layouts/15/onedrive.aspx

Are you able to check that one out for me?

**Comment by VesaJuvonen** [comment]
This is unfortunately by design. New experiences do not support JavaScript injection. This includes OneDrive for Business and Delve for now. Document library experience is still in discussion. If this is causing a challenge for you and you can't keep on using old experiences (tenant level option), would suggest to use UserVoice, so that feedback is collected with official processes. See for example following around new document library experience - https://sharepoint.uservoice.com/forums/329214-sites-and-collaboration/suggestions/13385364-allow-javascript-customization-and-css-branding-th.
