### ISSUE TITLE
Core.EmbedJavaScript - sub sites not working

### ISSUE THREAD

**Issue by roopeshperla** [OfficeDev/PnP#1488]
Hi, 

Working on JavaScript Injection through Add-In. Requirement was to have corporate level Footer. 

Used the concept of Java Script Inject and did implemented for a team site / dev site. Create a sub site within the root site collection but the JavaScript injected @ site collection level was not appearing in the sub site. 

Root Site Collection - Dev Site / Team Site
Sub Site - Team Site / Blog Site

**Comment by VesaJuvonen** [comment]
This is because that sample adds the user custom custom to Web object, not on the Site object. Will update the MSDN article around this with additional note, but if you change the code a bit to add the UserCustomAction to Site object, then the customization is available cross all the sites in site collection.
