### ISSUE TITLE
Cloud Provisioning Solution looses context when hosted inside the new Sites Dialog

### ISSUE THREAD

**Issue by SRennocks** [OfficeDev/PnP#15]
I can get the app to work standalone - except the Yammer piece, but when I try as a dialog from the "Sites" url all is not rosy. The dialog and content appear but the OK button does not function, the site urls do not change when you change site templates - I enabled uncommented the LoadModules call from the sites list selected index changed method but that did not help either. It appears that the page is not posting back.

The issue appears to be with SharePointContextProvider.Current.GetSharePointContext(httpContext) coming back null and the SPHasRedirectedToSharePoint query param = 1

**Comment by VesaJuvonen** [comment]
Issue which has been open for way too long. We have moved away from the patterns used with the Provisioning.Cloud.Sync application, since it was implemented using sync model, which timed out in the Azure. This is not really recommended pattern, so sample has been removed from the PnP guidance. Also the xml based configuration with this one was based on old model, which has been replaced with community driven PnP Provisioning Schema at https://github.com/OfficeDev/PnP-Provisioning-Schema.

Closing issue since it's no longer relevant.
