### ISSUE TITLE
OutlookNotificationAPI sample

### ISSUE THREAD

**Issue by fwd079** [OfficeDev/PnP#1548]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?

https://github.com/OfficeDev/PnP/tree/master/Samples/OutlookNotificationsAPI.WebAPI
#### Category

[ ] Bug
[•] Enhancement
#### Environment

[•] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

---

Hi here,

Hope you are fine, very quickly, I looked into code and went to following URL as well ( http://dev.office.com/patterns-and-practices-detail/7227 ) but cannot download the above mentioned URL as a **stand alone sample** and I do not want to download whole OfficeDev/Pnp repo, just this sample please.

Can you please point me to a URL where I can download this sample on its own, or something in that direction to help me with?

Kind Regards
Fawad

**Comment by VesaJuvonen** [comment]
There's no location for downloading individual samples, they are all in the same repository and GitHub does not provide capability to download only a folder from the repository, so there's really no way to make this happen. PnP repository is indeed pretty big, but not enormous either.

Closing this, since there's really nothing we can do with this request from PnP perspective.
