### ISSUE TITLE
Add-SPOTaxonomyField fails when adding the field second time after deleting it.

### ISSUE THREAD

**Issue by pankajsurti** [OfficeDev/PnP#311]
I added a taxonomy field using the Add-SPOTaxonomyField
Add-SPOTaxonomyField -DisplayName "Level" -Id "14BDF112-300B-48D2-9C8A-8620A2D87854" -InternalName "Level" -TermSetPath "Contoso.Intranet|Level" -Group "Contoso Site Columns" 
It added successfully.

I then deleted the field and tried to add it again, I got an error.

![12-11-2014 10-21-31 am](https://cloud.githubusercontent.com/assets/108044/5396409/b849866e-811f-11e4-8f08-c6c6f51948e4.jpg)

**Comment by pankajsurti** [comment]
Was this issue resolved? If resolved in which version? Or if any workaround is present?
There should be a way to add the Taxonomy Field twice with same Guid. It is very easy to reproduce the bug,.

**Comment by erwinvanhunen** [comment]
I just tried to reproduce the issue with the current dev branch but fail to raise the same issue. When looking at your code, it seems to be a pretty 'old' release already you're using as we changed the method CreateFieldBase<TField> already a few months ago. (2014-11-21 to be precise). I would recommend you to get the latest binary build from the powershell library (the January build is the latest based on the master branch) and try again. 

I tried to reproduce the issue like this:

```
PS C:\> Add-SPOTaxonomyField -List "Testing" -DisplayName "TaxTest" -InternalName "TaxTest" -TermSetPath "Demo|Test" -Id $guid

Title                          InternalName                   Id
-----                          ------------                   --
TaxTest                        TaxTest                        584ed7a8-b02c-4400-b403-3bbda2ada7a1


PS C:\> Remove-SPOField -Identity $guid -List "Testing"

Confirm
Delete field 'TaxTest'?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
PS C:\> Add-SPOTaxonomyField -List "Testing" -DisplayName "TaxTest" -InternalName "TaxTest" -TermSetPath "Demo|Test" -Id $guid

Title                          InternalName                   Id
-----                          ------------                   --
TaxTest                        TaxTest                        584ed7a8-b02c-4400-b403-3bbda2ada7a1
```

**Comment by jansenbe** [comment]
@pankajsurti : did you try using the latest version as proposed by @erwinvanhunen?

**Comment by pankajsurti** [comment]
Yes I have I am still getting the same issue.

**Comment by danbudimir** [comment]
This issue only manifested when attempting to re-create a taxonomy site column, I did not have any problems when re-creating a taxonomy columns on a list.  The fix was, prior to attempting to create, check to see if the column existed, if it did not then assume the possibility that it had been created earlier then deleted, get the supplied id and use it to check for the existence of the hidden field, if found delete the hidden field then allow the process to proceed.  I've tested and checked the fix into the dev branch.  Please note that you will have to re-compile the OfficeDevPnP.PowerShell project after getting latest.
