### ISSUE TITLE
Add-SPOFieldToContentType  throws The collection has not been initialized. It has not been requested or the request has not been executed error

### ISSUE THREAD

**Issue by SreedharMallangi** [OfficeDev/PnP#362]
I was able to add a site column to content type using Add-SPOFieldToContentType  using the code base I got a month ago. I got the latest code base yesterday and when I  ran the same command that I ran few weeks ago , it throws the following error. 

> Add-SPOFieldToContentType -Field "BAH_ICCategory" -ContentType "Intellectual Capital"
Add-SPOFieldToContentType : The collection has not been initialized. It has not been requested or the request has not
been executed. It may need to be explicitly requested.
At line:1 char:1
+ Add-SPOFieldToContentType -Field "BAH_ICCategory" -ContentType "Intellectual Cap ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-SPOFieldToContentType], CollectionNotInitializedException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.CollectionNotInitializedException,OfficeDevPnP.PowerShell.Co
   mmands.AddFieldToContentType

**Comment by erwinvanhunen** [comment]
I can confirm this being a bug in the Core library. It's been fixed in PR #363

**Comment by SreedharMallangi** [comment]
Great. Thanks for quick update. 

 I installed latest PnPPowerShellCommands16.msi on 1/5. I still see the issue. is it because latest MSI does not have the updated dlls? Am I missing anything here. Thanks for your help.

**Comment by erwinvanhunen** [comment]
Indeed, the latest available .MSI files don't have the latest code yet. 

The Pull Request is actually still waiting to be merged. After that has happened the core library has to be merged with the master branch. At that time we update the powershell installer files. 

We merge the dev branch with the master branch once a month and the last merge was actually a couple of days ago, meaning it will take a while before the fix is pushed out to the binary installers.

However, the moment the pull request has been merged into the dev branch you can build the dev branch yourself in Visual Studio. Then locate the old OfficeDevPnP.Core.dll file on your computer and replace that one with the one you just built in Visual Studio. That should fix your issue. The moment the installer has been updated you can just install the latest and you're set.

**Comment by jansenbe** [comment]
Pull request has been merged, closing this issue.

**Comment by GavinHaak** [comment]
Still an issue for me with the latest MSI....
