### ISSUE TITLE
Use of XElement instead of XmlDocument

### ISSUE THREAD

**Issue by nanddeepn** [OfficeDev/PnP#375]
Hello,
We had a Microsoft code review for one of our customer project yesterday (The project did not use PnP, but a farm solution using SSOM). The comments from MS recommends to use XElement instead of XmlDocument (on the base of Performance).
We at OfficeDev.PnP are using old XmlDocument way to handle xml.

Could you please advise which one is preferable way to go? (XElement or XmlDocument)?

**Comment by erwinvanhunen** [comment]
Many of the methods you find in PnP are based on older (used in production at customers) code, that's why you might see XmlDocument referenced. I personally prefer XElement over XmlDocument and would absolutely recommend to use XElement over XmlDocument. We should convert those methods that use XmlDocument to XElement.

**Comment by nanddeepn** [comment]
Thank you @erwinvanhunen for the detailed explanation.

**Comment by erwinvanhunen** [comment]
I started converting some of the methods that use XmlDocument to use XDocument instead. It provides more clearer and easier to read code too. I will close this issue now.

**Comment by nanddeepn** [comment]
Thank you @erwinvanhunen ,
Please let me know if I can share any load.
