### ISSUE TITLE
Guide for naming standards

### ISSUE THREAD

**Issue by erwinvanhunen** [OfficeDev/PnP#396]
We need to provide guidance for naming standards and categorization for samples, scenarios and solutions.

**Comment by SharePointRadi** [comment]
This is really important. Since I haven't participated in the project and have missed on many meetings, I struggle to make sure I'm naming things as expected and putting them in the right bucket. I also feel silly to ask the questions as they seem of low importance, so a guide would really help. 

With no guide there is usually expectation that during a Pull request someone would do this.

**Comment by jansenbe** [comment]
We used to have some 'basic' guidance back in the Office AMS time...let me do some digging

**Comment by westerdaled** [comment]
I would be interested in this too when advising my clients. btw I heard there is a ( world conquering) dictator lurking with the PnP team - so time to rise up ;-)

**Comment by jansenbe** [comment]
LOL

**Comment by frankmarasco** [comment]
LOL

**Comment by VesaJuvonen** [comment]
Closing this one to clear up backlog for future efforts.
