### ISSUE TITLE
Save site as remote provisioning xml

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP#459]
After the release of the site provision engine with the remote provisioning xml support, we should be looking into providing "save site as a template" capability to extract existing sites to needed xml format.

Something to look into with April / May release schedules.

**Comment by VesaJuvonen** [comment]
Pseudo process: 

When "Save site as a template" is called provider hosted apps will analyze the current site and will create needed remote provisioning xml file with the supported format. This will be also stored to specific hidden folder in site collection level, so that end users can save templates and they can then use them as needed... provider hosted app which can be used to provision centrally deployed templates will also check if there's site collection level templates in the current site collection and will show them as optional templates, if some exists.

**Comment by SharePointRadi** [comment]
Very interesting. We have implemented something similar using PowerShell.Commands. I'll see if we can submit it as a sample for you to review. I think it's important to define the XML structure.

**Comment by hhtech1** [comment]
What about using the current built-in functionality of SharePoint (Save Site As Template), which customers are familiar with. And then in your provisioning engine optionally allow a site type to be based on on template (.wsp) saved in this way. In other words, some site types can be based purely on remove provisioning XML, where as some site types can be based on a combination of .wsp package (so that customer can easily deliver their custom team site template) and remote provisioning XML. We actually have this implemented (XML structure and handling), Vesa I could quickly show this to you (also I'm not yet sure how much we can share here).
There is one related issue (CSOM gap) remaining, which is discussed here:
https://officespdev.uservoice.com/forums/224641-general/suggestions/5633494-add-support-for-sandbox-solutions-upload-and-activ

**Comment by erwinvanhunen** [comment]
As we have this functionality now, and it's efforts are ongoing, I will close this issue.

**Comment by VesaJuvonen** [comment]
Reopened... we do not have a link in site settings and not a sample which will show how end users can save a template, which is then visible in the Sub site creation. Working on the full story for comprehensive solution, but end user functionality is not there currently even thought API level implementation does exists.

Since this is not available, issue reopened.

**Comment by erwinvanhunen** [comment]
I was a bit to trigger happy :-)

**Comment by VesaJuvonen** [comment]
Reference implementation done at the PnP Partner Pack (https://github.com/OfficeDev/PnP-Partner-Pack), so closing this one.
