### ISSUE TITLE
ASP.Net Forms sample that uses O365 API

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP#465]
There are plenty of MVC samples out and we have one as well in PnP, but the amount of ASP.Net Forms samples is almost nil. Looking for volunteers to extend the existing Office365Api.Overview sample with a simple ASP.Net forms implementation.

If you take up the challenge, please leave a note here so that we don't have multiple people doing the same :)

**Comment by PaoloPia** [comment]
Count me in 😊...I'll do it in the next upcoming days.

Inviata dal mio Windows Phone
________________________________
Da: Bert Jansen<mailto:notifications@github.com>
Inviato: ‎20/‎02/‎2015 08:56
A: OfficeDev/PnP<mailto:PnP@noreply.github.com>
Oggetto: [PnP] ASP.Net Forms sample that uses O365 API (#465)


There are plenty of MVC samples out and we have one as well in PnP, but the amount of ASP.Net Forms samples is almost nil. Looking for volunteers to extend the existing Office365Api.Overview sample with a simple ASP.Net forms implementation.

If you take up the challenge, please leave a note here so that we don't have multiple people doing the same :)

**Comment by pbjorklund** [comment]
And there is the opposite thing with PnP samples, lot's of webforms with all the logic hidden in the ```Default.aspx.cs```. Would it be an idea to transform to use a separate class library project in the solution that one could include/copy to use in an mvc/console/etc?

Easy to just keep using webforms if everything is in there and working, vs being forced into the MVC conventions from the getgo if it's just a simple change.

**Comment by jansenbe** [comment]
Closed thanks to Paolo's updated O365 sample. See https://github.com/OfficeDev/PnP/tree/dev/Samples/Office365Api.Overview/Office365Api.WebFormsDemo
