### ISSUE TITLE
Branding.ApplyBranding for Non Publishing sites 

### ISSUE THREAD

**Issue by ventil8** [OfficeDev/PnP#550]
Could the above be adapted to work for Non publishing sites?

**Comment by VesaJuvonen** [comment]
Since this sample would work with non-publishing sites, I'll close this one for now. Master page deployment target is the same and key difference is around the fact that you'll need to deploy master page to each site when publishing features are not used. Second dimension is to update MasterUrl property, which impacts normal pages. CustomMasterUrl is then for publishing pages.

If there's any other aspects which should be covered, we can re-open this issue. Thx for submitting this one.
