### ISSUE TITLE
Core.TaxonomyMenu does not display in Team Site On Premises

### ISSUE THREAD

**Issue by sebastianrogers** [OfficeDev/PnP#572]
I have disabled the Minimal Download Strategy but the menu only displays in _layouts pages and not the SitePages.

**Comment by sebastianrogers** [comment]
Additional info the Team Site loads sp.userprofiles.debug.js and not sp.userprofiles.js.

The loading code uses:

SP.SOD.executeOrDelayUntilScriptLoaded(function () {
                        SP.SOD.registerSod('sp.userprofiles.js', SP.Utilities.Utility.getLayoutsPageUrl('sp.userprofiles.js'));
                        SP.SOD.executeFunc('sp.userprofiles.js', false, function () {
                            deferred.resolve();
                        });
                    }, 'sp.js');

Hence the actual menu code never runs.

**Comment by VesaJuvonen** [comment]
I'm really sorry for the delay on getting any response around this. This is now more than year ago and not sure if this is still valid. Core.Taxonomy menu from conceptual perspective will absolutely work in on-premises as well, but it might be that some builds (CUs) have been having some regressions, since we should obviously not load .debug.js in the on-premises.

**Comment by sebastianrogers** [comment]
Hi Vesa

Thanks for getting back to me, I'll retest this on a more recent CU and get back to you.

Cheers

Sebastian
