### ISSUE TITLE
GetRealmFromTargetUrl in TokenHelper.cs should not assume GUID for Realm

### ISSUE THREAD

**Issue by Markus-MEEQIT** [OfficeDev/PnP#605]
On-premises it is possible to set Realm to any string using Set-SPAuthenticationRealm cmdlet. GetRealmFromTargetUrl in TokenHelper.cs from Visual Studio templates does on the other hand do a Guid.TryParse (as well as assuming a length of 36) which effectively means that a GUID is required.

Either it should be considered a bug that Set-SPAuthenticationRealm allows anything but a GUID to be set or TokenHelper.cs should be considered flawed for on-prem installations. Personally I would prefer TokenHelper.cs to be updated as on-prem it is really nice to set Realm to something readable that indicates its origin (consider troubleshooting in multi farm setups using shared hosting for provider hosted Apps).

Resolving the issue could be done by simply changing this part of GetRealmFromTargetUrl:

string targetRealm = bearerResponseHeader.Substring(realmIndex, 36);
Guid realmGuid;

if (Guid.TryParse(targetRealm, out realmGuid))
{
    return targetRealm;
}

into something like this:
string[] targetRealm = bearerResponseHeader.Split('\"');
return targetRealm[1];

**Comment by erwinvanhunen** [comment]
Hej Markus!

That's a valid point you're making. However, we decided to use the default TokenHelper.cs in the PnP Core library, e.g. the one that Visual Studio gives us. Basically very TokenHelper.cs out there has this issue. It helps if you create an entry on uservoice: https://officespdev.uservoice.com/, while we will also bring this to the attention of the appropriate people within Microsoft.

Tack!

/Erwin

**Comment by VesaJuvonen** [comment]
Hi Markus,
like Erwin communicated, we will definitely loop this also through using internal rounds, but at the same time it would be great if you'd crate a user voice entry for this, for tracking purposes. That means that it will be officially tracked in our MS internal meetings. 

Thanks also from my behalf. This is really good feedback with clear suggestion on how to get it resolved. I'll close this now from the PnP tracking, since we cannot really fix this "oob" component, but we will certainly follow up on this one.
