### ISSUE TITLE
Culture dependancy with the usage of web.Lists.GetByTitle('Style Library') 

### ISSUE THREAD

**Issue by levesquesamuel** [OfficeDev/PnP#815]
web.Lists.GetByTitle("Style Library") will only work in an english site.

Lists should be retrieved by their URL to make the code less dependant on the culture.

Same thing applies for site assets.

**Comment by StfBauer** [comment]
Thank you for pointing this out. This is just an inaccuracy in the documentation the code contains the following line of code that should work on any case.
List assetLibrary = web.Lists.EnsureSiteAssetsLibrary();
            web.Context.Load(assetLibrary, l => l.RootFolder);

Not only that Site Assets title cannot be found in non-english site. It will also fail on Publishing Sites because Site Assets doesn't exist by default on publishing pages such as publishing portal without collaboration lists enabled.

**Comment by levalencia** [comment]
it happens to me as well

**Comment by SebasAcevedo** [comment]
But you can use web.Lists.GetListByUrl("/Style Library/")
