### ISSUE TITLE
Hi team , Core.TaxonomyPicker is a provider hosted app, Can we achieve the same functionality in Sharepoint Hosted app

### ISSUE THREAD

**Issue by 1112ravichandra** [OfficeDev/PnP#869]
Hi Team,

we are developing custom forms for a list using sharepoint hosted app ,in one of the form (for new item ) we need taxonomy control,

Please team help me to replicate it in SharePoint hosted app.

**Comment by VesaJuvonen** [comment]
Hi 1112ravichandra, you can actually use out of the box fields in the SP hosted apps, so you do not have to necessarily build any custom controls for this one. I'd suggest to ask this question in the PnP Yammer group at http://aka.ms/OfficeDevPnPYammer and we can provide more insights.

Since this is rather a development time support question and not actual issue in the PnP code base or any of the samples, will close the issue.

**Comment by 1112ravichandra** [comment]
Hi,
please let me know the out of the box field control for the same.
