### ISSUE TITLE
FileSystemConnector GetFile method on webpart files throws error when webpart is added to page

### ISSUE THREAD

**Issue by rfjschouten** [OfficeDev/PnP#974]
I try to use the FileSystemConnector and use the GetFile method in order to grap a webpart file (exported through the SharePoint UI). When I create a new Page object, add the webpart to the constructor and add the file to the template, the template gets correctly created (when I view the saved xml version of it). If I try and apply the template to a web object, I receive an error that the webpart file is not correct and cannot be imported (default message). When I grap the same webpart file using System.IO.File.ReadAllText and put that string in the contents of the webpart, add it to the page and template, it applies the template correctly.

See below thread for context and repro:
https://www.yammer.com/itpronetwork/#/Threads/show?threadId=550122342

**Comment by VesaJuvonen** [comment]
Sorry Robert for way too long reaction times around this issue. We have done significant refactoring of the Core component since this issue and most likely it has been properly fixed. If that's not the case, would ask you to create a new issue in the Core Component repository to avoid issue getting hidden. Core component repository is at https://github.com/OfficeDev/PnP-sites-core.
