### ISSUE TITLE
Provisioning Engine - what If?

### ISSUE THREAD

**Issue by iddycol** [OfficeDev/PnP#987]
I'm not sure if this is the right way to suggest this, however I think it would be useful if the provisioning engine included a "what if" function. Currently we can use the engine to read form an apply our models to a remote site. That's all very final, with our changes committed and the potential for damage and unintended consequences on the target. I think the ability to run the provisioning models with a what if switch and receive a report of the changes that would be made in the target environment if a model is applied would be useful. Related to this, the code appears to generally follow an update if present approach. Some more explicit and fine grained control of this would be nice. For some artefacts a delete / replace or ignore approach may be appropriate.

**Comment by braegelno5** [comment]
that's a good idea, what i have missed not only one time is a transaction scope for our changes to the target site.. but this we must also implement in the engine, its not supported from sp..

**Comment by VesaJuvonen** [comment]
We have intentionally not implemented that many delete/remove scenarios, since those are typically not supported with SharePoint even with feature framework. Delta handling has been improved nicely during the journey, so the what-if handling should be pretty well there. Obviously there's always room for improvements. Will close up this one for now and we can continue discussion in PnP Yammer group if needed.
