### ISSUE TITLE
Mark Provisioning Object Handlers as public ?

### ISSUE THREAD

**Issue by iddycol** [OfficeDev/PnP#990]
Consider marking the provisioning object handler classes as public so that they can be used outside the PnP assembly and independently of each other.

**Comment by erwinvanhunen** [comment]
We on purpose decided not to, due to the fact that the object handlers have dependencies between each other. Especially the ListInstanceObject handler has dependencies on 2 other object handlers.

If you still want to use an object handler as is, you can consider getting the source code for the core library, and include a copy of the code in your solution. Then add an addtional line in the AssemblyInfo.cs file allowing internals to be visible to your assembly. We do that for instance to be able to unit test the internals.

```
[assembly: InternalsVisibleTo("OfficeDevPnP.Core.Tests")]
```

**Comment by iddycol** [comment]
Thanks
